# plugins service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plugin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: plugin-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: plugin-binding
subjects:
- kind: ServiceAccount
  name: plugin
  namespace: default
roleRef:
  kind: Role
  name: plugin-manager
  apiGroup: rbac.authorization.k8s.io